### ISSUE TITLE
context.activity.type == 'conversationUpdate': is not working

### ISSUE THREAD

**Issue by kkhzz1004** [tdurnford/python-echobot-with-state#1]
Helllo

I post my bot on Azure. when i try on Bot-emulator, context.activity.type is working
 but not on the Azure. 

![error_pic](https://user-images.githubusercontent.com/30832990/54005349-66635400-419c-11e9-968e-ad3aa9eac3c0.png)  i mean it comes together, it must be first when user enter the chat.

please help me to fix it. 
thanks

**Comment by tdurnford** [comment]
@kkhzz1004 

Congrats on deploying a Python Bot to Azure. Glad to see the deployment directions worked for someone else. 

In regards to your issue, different channels - the Emulator, Test in Web Chat, Teams, Skype, Facebook, etc - all handle welcome messages differently. Channels like the Emulator send the `ConversationUpdate` event to the Bot when the user joins the conversation while other channels such as Teams and Test in Web Chat send the event after the user messages the bot. This is why you see the welcome message in the emulator before the user messages the bot and afterward in Test in Web Chat. Unfortunately, there is no way to alter this behavior.

Hope this helps!
